language: rust 
rust:
     - stable
     - nightly
sudo: false
env:
  global:
   - "FTP_USER=user"
   - "FTP_PASSWORD=password"
script: 
     - cargo build
     - cargo test
     - cargo run

after_success:
    "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://sitename.com/diectory/myfile "
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy DEPLOY_REPO_URI_GOES_HERE
  - git push deploy    
