language: rust 
rust:
     - stable
     - nightly
sudo: false
script: 
     - cargo build
     - cargo test
     - cargo run
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
  	branch: develop



     
     
